CREATE TABLE CATALOGO_DIRECCION(
ID_CATALOGO INT PRIMARY KEY identity,
NUM_CASA VARCHAR(50),
CALLE_AVENIDA VARCHAR(50),
CIUDAD VARCHAR(50),
COLONIA VARCHAR(50),
CODIGO_POSTAL INT,
DEPARTAMENTO VARCHAR(50),
MUNICIPIO VARCHAR(50),
ESTADO VARCHAR(50),
)
GO

CREATE TABLE PERSONAL(
ID_PERSONAL INT PRIMARY KEY identity,
ID_CATALOGO INT,
DIRECCION VARCHAR(50),
NOMBRE_PERSONAL VARCHAR(50),
APELLIDO_PERSONAL VARCHAR (50),
FECHA_NACIMIENTO VARCHAR(50),
FECHA_CONTRATACION VARCHAR(50),
TELEFONO_PERSONAL INT,
EMAIL_PERSONAL VARCHAR(50),
FECHA_BAJA VARCHAR(50),
ESTADO VARCHAR(50),
PUESTO VARCHAR(50)
)
GO

CREATE TABLE CONTRATO(
ID_CONTRATO INT PRIMARY KEY identity,
ID_CLIENTE INT,
ID_PERSONAL INT,
ID_PLACA INT,
SESION INT,
FECHA_INICIO VARCHAR(50),
FECHA_FIN VARCHAR(50),
COSTO INT,
ESTADO VARCHAR(50)
)
GO

CREATE TABLE VEHICULO(
ID_PLACA INT PRIMARY KEY identity,
MARCA VARCHAR(50),
MODELO VARCHAR(50),
ANIO VARCHAR(5),
FECHA_COMPRA VARCHAR(50)
)
GO

CREATE TABLE CLASE(
ID_CLASE INT PRIMARY KEY identity,
ID_CLIENTE INT,
ID_CONTRATO INT,
HORA_INICIO VARCHAR(50),
HORA_FIN VARCHAR(50),
FECHA VARCHAR(50)
)
GO

CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY identity,
NOMBRE_COMPLETO VARCHAR(50),
DIRECCION VARCHAR(50),
FECHA_NACIMIENTO VARCHAR(50),
TELEFONO INT,
EMAIL VARCHAR (50),
ESTADO VARCHAR(50)
)
GO 

CREATE TABLE REGISTRAR_PAGO(
ID_PAGO INT PRIMARY KEY identity,
ID_CLIENTE INT,
ID_CONTRATO INT,
FECHA_PAGO VARCHAR(50),
TIPO_PAGO VARCHAR(50),
MONTO INT
)
GO

ALTER TABLE PERSONAL ADD CONSTRAINT REGISTRO_DIRECCION FOREIGN KEY (ID_CATALOGO) REFERENCES CATALOGO_DIRECCION (ID_CATALOGO)
GO
ALTER TABLE CONTRATO ADD CONSTRAINT CONTRATO_PERSONAL FOREIGN KEY (ID_PERSONAL) REFERENCES  PERSONAL (ID_PERSONAL)
GO
ALTER TABLE CONTRATO ADD CONSTRAINT CONTRATO_VEHICULO FOREIGN KEY (ID_PLACA) REFERENCES VEHICULO (ID_PLACA)
GO
ALTER TABLE REGISTRAR_PAGO ADD CONSTRAINT PAGO_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO (ID_CONTRATO)
GO
ALTER TABLE REGISTRAR_PAGO ADD CONSTRAINT PAGO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
GO
ALTER TABLE CLASE ADD CONSTRAINT CLASE_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO (ID_CONTRATO)
GO
ALTER TABLE CLASE ADD CONSTRAINT CLASE_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
GO
ALTER TABLE CONTRATO ADD CONSTRAINT CONTRATO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
GO


INSERT INTO CATALOGO_DIRECCION VALUES (1001, '10-20', '10', 'GUATEMALA', 'COLONIA 10', 100001, 'GUATEMALA', 'GUATEMALA', 'ACTIVO')
INSERT INTO CATALOGO_DIRECCION VALUES (1002, '10-21', '11', 'GUATEMALA', 'COLONIA 11', 100001, 'GUATEMALA', 'COBAN', 'ACTIVO')

INSERT INTO PERSONAL VALUES (2001,1001,'20 CALLE 10-20 ZONA 5', 'Leonel', 'Marcos', '10/12/1996', '06/01/2021', 55879685, 'Leonel@gmailcom', '06/01/2025','ACTIVO', 'INSTRUCTOR')
INSERT INTO PERSONAL VALUES (2002,1002,'25 CALLE 10-30 ZONA 5', 'Carlos', 'Beteta', '22/01/1977', '06/01/2021', 22015756, 'carlos@gmailcom', '06/01/20250','ACTIVO', 'INSTRUCTOR')

INSERT INTO CLIENTE VALUES (5001, 'Henry del Valle', '63 Ilusiones', '25/06/1991', 50129026,'haduchiha@live.com', 'ACTIVO')

INSERT INTO VEHICULO VALUES (3001, 'Honda', 'Civic', '2020', '04/04/2020')
INSERT INTO VEHICULO VALUES (3002, 'KIA', 'PICANTO', '2011', '05/07/2011')

INSERT INTO CONTRATO VALUES (4001,5001,2001, 3001,30,'01/05/2021','31/05/2021', 3000, 'ACTIVO')

INSERT INTO CLASE VALUES (6001, 5001,4001, '07:00', '09:00','05/05/2021')

INSERT INTO REGISTRAR_PAGO VALUES (7001,5001,4001,'19/05/2021', 'efectivo',3000)


SELECT * FROM CATALOGO_DIRECCION
SELECT * FROM PERSONAL
SELECT * FROM VEHICULO
SELECT * FROM CLIENTE
SELECT * FROM CONTRATO
SELECT * FROM CLASE
SELECT * FROM REGISTRAR_PAGO


CREATE TABLE users (
  id INT primary key identity,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) DEFAULT NULL,
  cui VARCHAR(45) default Null,
  user_name VARCHAR(45) NULL,
  email VARCHAR(100) unique,
  password VARCHAR(250) NULL DEFAULT NULL,
  birthdate DATE NULL DEFAULT NULL,
  status int NULL DEFAULT 1,
  verified int NULL DEFAULT 0,
  remember_token int NULL DEFAULT 0,
  api_token VARCHAR(250) DEFAULT NULL,
  email_verified_at date NULL
)


ALTER PROCEDURE SP_REGISTRAR_CONTRATO 
@ID_CONTRATO AS INT,
@SESION AS INT,
@ID_PERSONAL AS INT,
@ID_PLACA AS INT,
@FECHA_INICIO AS VARCHAR(50),
@FECHA_FIN AS VARCHAR(50),
@COSTO AS INT,
@ESTADO AS VARCHAR(50),
@ID_CLIENTE AS INT

AS
SET NOCOUNT ON

BEGIN TRAN --INICIO TRANSACCION
IF (SELECT ID_CONTRATO
FROM CONTRATO
WHERE ID_CONTRATO = @ID_CONTRATO) = @ID_CONTRATO
BEGIN
ROLLBACK TRAN --TRANSACCION REVOCADA
PRINT ('ID CONTRATO YA EXISTE')
END
	IF(SELECT CONTRATO.ID_CLIENTE
		FROM CONTRATO
		LEFT JOIN CLIENTE ON CLIENTE.ID_CLIENTE = CONTRATO.ID_CLIENTE
		WHERE CONTRATO.ID_CLIENTE = @ID_CLIENTE 
		AND
		CLIENTE.ESTADO = 'INACTIVO') = @ID_CLIENTE
	BEGIN
	ROLLBACK TRAN --TRANSACCION REVOCADA
	PRINT ('ESTADO DEL CLIENTE INACTIVO')
	END

		ELSE
		INSERT INTO CONTRATO VALUES (
		@ID_CONTRATO,
		@SESION,
		@ID_PERSONAL,
		@ID_PLACA,
		@FECHA_INICIO,
		@FECHA_FIN,
		@COSTO,
		@ESTADO,
		@ID_CLIENTE)
		COMMIT TRAN --TRANSACCION COMPLETADA


	EXEC SP_REGISTRAR_CONTRATO 11, 10, 1, 101, '01/01/2021', '31/12/2021', 800, 'ACTIVO', 3

	


---CREACION DE INDEX--
CREATE NONCLUSTERED  INDEX IDX_FECHAS ON CONTRATO(FECHA_INICIO , FECHA_FIN, ID_CLIENTE)
EXEC SP_HELPINDEX CONTRATO
SELECT FECHA_INICIO,FECHA_FIN,ID_CLIENTE FROM CONTRATO